baseURL = 'https://kochenmit.style/'
theme = 'lugo'
languageCode = 'de-DE'
title = 'Kochen mit Style'

[params]
  favicon = "/favicon.svg"
  stylesheet = "/style.css"
  indexarticles = 50
  taglist = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
     
