name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push to master (including merged PRs)
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:



jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.STYLE_SSH }}

      - name: Connect to Server and Run Commands
        run: |
          ssh -t -p ${{ secrets.STYLE_PORT }} ${{ secrets.STYLE_USER }}@kochenmit.style "\
           cd kochenmit.style \
            && git stash \
            && git pull --force origin master \
            &&  hugo -s . -t $HOME/glulo -d /var/www/kochenmitstyle/ --cacheDir ~/hugocache"
